=== difdaystart/great-code/ECMS/CUSTOMS/广州/BC-2016.3.7/CBEC202_DeclarationResponse.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="urn:gacc:datamodel:GZ:CBEC202:1" targetNamespace="urn:gacc:datamodel:GZ:CBEC202:1" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!--跨境电子商务通用申报回执报文定义-->
	<xs:element name="CBEC">
		<xs:annotation>
			<xs:documentation>跨境电子商务报文(root)</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Head" type="HeadType">
					<xs:annotation>
						<xs:documentation>报文头数据段</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Response" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>回执数据段</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="CreationTime" type="xs:dateTime">
								<xs:annotation>
									<xs:documentation>回执生成时间
YYYY-MM-DDThh:mm:ss.fff+08:00</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="Declaration">
								<xs:annotation>
									<xs:documentation>申报/报送数据段</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Declarant" type="DeclarantType" minOccurs="0">
											<xs:annotation>
												<xs:documentation>申报/报送者数据段</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="ECommercePlatform" minOccurs="0">
											<xs:annotation>
												<xs:documentation>电商平台数据段</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:sequence>
													<xs:element name="InternetDomainName">
														<xs:annotation>
															<xs:documentation>电商平台互联网域名</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1"/>
																<xs:maxLength value="100"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="PaymentCompany" minOccurs="0">
											<xs:annotation>
												<xs:documentation>支付公司数据段</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:sequence>
													<xs:element name="RegistrationNumber" minOccurs="0">
														<xs:annotation>
															<xs:documentation>支付公司备案号</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="0"/>
																<xs:maxLength value="30"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="Name">
														<xs:annotation>
															<xs:documentation>支付公司名称</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1"/>
																<xs:maxLength value="100"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="LogisticsCompany" minOccurs="0">
											<xs:annotation>
												<xs:documentation>物流公司数据段</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:sequence>
													<xs:element name="RegistrationNumber">
														<xs:annotation>
															<xs:documentation>物流公司备案号</xs:documentation>
														</xs:annotation>
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="1"/>
																<xs:maxLength value="30"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="DocumentID">
											<xs:annotation>
												<xs:documentation>申报/报送单据编号</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="128"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="DocumentTypeCode">
											<xs:annotation>
												<xs:documentation>申报/报送单据类型</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="10"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Main" type="BaseResponseType">
								<xs:annotation>
									<xs:documentation>主回执数据段</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="Item" minOccurs="0" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>申报/报送项回执数据段</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ID">
											<xs:annotation>
												<xs:documentation>申报/报送项编号</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="30"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Response" type="BaseResponseType">
											<xs:annotation>
												<xs:documentation>回执信息数据段</xs:documentation>
											</xs:annotation>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="HeadType">
		<xs:annotation>
			<xs:documentation>报文头类</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="MessageID">
				<xs:annotation>
					<xs:documentation>报文编号</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="64"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="FunctionCode">
				<xs:annotation>
					<xs:documentation>报文功能代码</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="2"/>
						<xs:enumeration value="2"/>
						<xs:enumeration value="3"/>
						<xs:enumeration value="5"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="MessageType" fixed="CBEC202">
				<xs:annotation>
					<xs:documentation>报文类型代码</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="SenderID">
				<xs:annotation>
					<xs:documentation>发送方代码</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="30"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="ReceiverID" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>接收方代码</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="30"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="SendTime" type="xs:dateTime">
				<xs:annotation>
					<xs:documentation>发送时间
YYYY-MM-DDThh:mm:ss.fff+08:00</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Version">
				<xs:annotation>
					<xs:documentation>报文版本号</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="DeclarantType">
		<xs:annotation>
			<xs:documentation>申报者类</xs:documentation>
		</xs:annotation>
		<xs:choice>
			<xs:element name="Company">
				<xs:annotation>
					<xs:documentation>公司</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="RegistrationNumber">
							<xs:annotation>
								<xs:documentation>备案号</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:minLength value="1"/>
									<xs:maxLength value="30"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Person">
				<xs:annotation>
					<xs:documentation>个人</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Name">
							<xs:annotation>
								<xs:documentation>名称</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:minLength value="1"/>
									<xs:maxLength value="100"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="IDNumber">
							<xs:annotation>
								<xs:documentation>证件号码</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="IDNumberType">
										<xs:attribute name="TypeCode" use="required">
											<xs:annotation>
												<xs:documentation>证件类型代码</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:minLength value="1"/>
													<xs:maxLength value="2"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:attribute>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="BaseResponseType">
		<xs:annotation>
			<xs:documentation>基本回执信息类</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Code">
				<xs:annotation>
					<xs:documentation>回执类型代码</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="5"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Data" minOccurs="0">
				<xs:annotation>
					<xs:documentation>回执数据</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="0"/>
						<xs:maxLength value="256"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Text">
				<xs:annotation>
					<xs:documentation>回执文本</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
						<xs:maxLength value="8000"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="IDNumberType">
		<xs:annotation>
			<xs:documentation>证件号码类</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="30"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== difdaystart/great-code/ECMS/CUSTOMS/广州/BC-2016.3.7/回执报文样例/CBEC202_1p0_5100_20151110154927_0000027（14接收成功）.xml
<?xml version="1.0" encoding="UTF-8"?>
<CBEC xsi:schemaLocation="urn:gacc:datamodel:GZ:CBEC202:1 CBEC202_DeclarationResponse.xsd" xmlns="urn:gacc:datamodel:GZ:CBEC202:1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Head>
		<MessageID>CBEC202_1p0_5100_20151110154927_0000027</MessageID>
		<FunctionCode>2</FunctionCode>
		<MessageType>CBEC202</MessageType>
		<SenderID>5100</SenderID>
		<ReceiverID>PTE51011400000000001</ReceiverID>
		<SendTime>2015-11-10T15:49:27.404</SendTime>
		<Version>1.0</Version>
	</Head>
	<Response>
		<CreationTime>2015-11-10T15:49:27.404</CreationTime>
		<Declaration>
			<Declarant>
				<Company>
					<RegistrationNumber>PTE51011400000000001</RegistrationNumber>
				</Company>
			</Declarant>
			<ECommercePlatform>
				<InternetDomainName>www.xx.com</InternetDomainName>
			</ECommercePlatform>
			<DocumentID>ad23a040a57641ceb07d5cfa832fdc</DocumentID>
			<DocumentTypeCode>CBEC102</DocumentTypeCode>
		</Declaration>
		<Main>
			<Code>14</Code>
			<Text>清单:ad23a040a57641ceb07d5cfa832fdc接收成功。</Text>
		</Main>
	</Response>
</CBEC>

=== difdaystart/great-code/ECMS/CUSTOMS/广州/BC-2016.3.7/回执报文样例/CBEC202_1p0_5100_20151110154951_0000033（13其它退单）.xml
<?xml version="1.0" encoding="UTF-8"?>
<CBEC xsi:schemaLocation="urn:gacc:datamodel:GZ:CBEC202:1 CBEC202_DeclarationResponse.xsd" xmlns="urn:gacc:datamodel:GZ:CBEC202:1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Head>
		<MessageID>CBEC202_1p0_5100_20151110154951_0000033</MessageID>
		<FunctionCode>2</FunctionCode>
		<MessageType>CBEC202</MessageType>
		<SenderID>5100</SenderID>
		<ReceiverID>PTE51011400000000001</ReceiverID>
		<SendTime>2015-11-10T15:49:51.770</SendTime>
		<Version>1.0</Version>
	</Head>
	<Response>
		<CreationTime>2015-11-10T15:49:51.770</CreationTime>
		<Declaration>
			<Declarant>
				<Company>
					<RegistrationNumber>IE150210000000</RegistrationNumber>
				</Company>
			</Declarant>
			<ECommercePlatform>
				<InternetDomainName>www.xx.com</InternetDomainName>
			</ECommercePlatform>
			<LogisticsCompany>
				<RegistrationNumber>IE150210000000</RegistrationNumber>
			</LogisticsCompany>
			<DocumentID>99087665</DocumentID>
			<DocumentTypeCode>CBEC102</DocumentTypeCode>
		</Declaration>
		<Main>
			<Code>13</Code>
			<Text>清单中的运单号[及物流公司备案号]已报关，不接受重复申报！(运单号:123456)</Text>
		</Main>
	</Response>
</CBEC>

=== difdaystart/great-code/ECMS/CUSTOMS/广州/BC-2016.3.7/回执报文样例/CBEC202_1p0_5100_20151112161304_0000018（16xsd校验不通过）.xml
<?xml version="1.0" encoding="UTF-8"?>
<CBEC xsi:schemaLocation="urn:gacc:datamodel:GZ:CBEC202:1 CBEC202_DeclarationResponse.xsd" xmlns="urn:gacc:datamodel:GZ:CBEC202:1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Head>
		<MessageID>CBEC202_1p0_5100_20151112161304_0000018</MessageID>
		<FunctionCode>2</FunctionCode>
		<MessageType>CBEC202</MessageType>
		<SenderID>5100</SenderID>
		<ReceiverID>PTE51011400000000001</ReceiverID>
		<SendTime>2015-11-12T16:13:04.957</SendTime>
		<Version>1.0</Version>
	</Head>
	<Response>
		<CreationTime>2015-11-12T16:13:04.957</CreationTime>
		<Declaration>
			<Declarant>
				<Company>
					<RegistrationNumber>PTE51011400000000001</RegistrationNumber>
				</Company>
			</Declarant>
			<DocumentID>CBEC102_1p0_PTE51011400000000001_20151112153149042_7104183.xml</DocumentID>
			<DocumentTypeCode>CBEC100</DocumentTypeCode>
		</Declaration>
		<Main>
			<Code>16</Code>
			<Text>cvc-type.3.1.3: 元素 'RegistrationNumber' 的值 '' 无效。</Text>
		</Main>
	</Response>
</CBEC>
